export const TRAVEL_VOCABULARY = {
  fullTrip: [
    'trip plan',
    'full trip',
    'plan a trip',
    'plan my trip',
    'book a trip',
    'itinerary',
    'travel schedule',
    'schedule my trip',
    'plan everything',
  ],
  flight: [
    'flight',
    'airline',
    'departure',
    'arrive',
    'airport',
    'ticket',
    'round trip',
    'return flight',
    'one way',
  ],
  hotel: [
    'hotel',
    'room',
    'booking',
    'check-in',
    'check-out',
    'overnight',
    'accommodation',
    'stay',
    'hostel',
  ],
  weather: ['weather', 'forecast', 'temperature', 'climate', 'rain', 'humidity', 'hot', 'cold'],
  places: [
    'attractions',
    'restaurant',
    'cafe',
    'bar',
    'shopping',
    'nightlife',
    'activity',
    'sightseeing',
    'places to visit',
    'landmarks',
    'hidden gems',
    'what to see',
    'where to eat',
  ],
  tips: [
    'tips',
    'advice',
    'local tips',
    'travel tips',
    'tip',
    'etiquette',
    'currency',
    'safety',
    'what to know',
  ],
  route: [
    'route',
    'directions',
    'stops',
    'tour',
    'move between',
    'get from',
    'walking tour',
    'sightseeing tour',
    'day tour',
  ],
  destinationExplorer: [
    'explore',
    'tell me about',
    'what is it like',
    "what's it like",
    'destination overview',
    'destination guide',
    'discover',
    'overview of',
    'visit',
    'travel to',
    'about the city',
    'city guide',
  ],
} as const;

export type TravelIntent = keyof typeof TRAVEL_VOCABULARY;

export const buildVocabularySection = (): string =>
  Object.entries(TRAVEL_VOCABULARY)
    .map(([intent, keywords]) => `- ${intent}: ${keywords.join(', ')}`)
    .join('\n');
